#!/bin/bash

help() {
    echo -e "Usage $1 {options}:"
    echo -e ""
    echo -e "Arguments:"
    echo -e "-l, --list\t\t\t\tList all availables environments"
    echo -e "-p, --packages {environment}\t\tShow instaled packages"
    echo -e "-a, --activate {environment}\t\tActivate the given environment"
    echo -e "-c, --create {python_version} {name}\tCreate a new environment"
    echo -e "-i, --interpreter\t\t\tShow all availables interpreters"
    echo -e "-d, --delete {environment}\t\tDelete the given environment"
    echo -e "-v, --version\t\t\t\tShow the version number and exit"
    echo -e "-h, --help\t\t\t\tShow this help and exit"

}

case "$1" in
    --list | -l)

        (
            source "env_wrapper.sh"
            list_environments
        )
        cd - > /dev/null
        ;;
    --packages | -p)
        (
            source "env_wrapper.sh"
            list_packages $2
        )
        cd - > /dev/null
        ;;
    --activate | -a)

        env_cmd=$(source "env_wrapper.sh"; get_environment_activation $2)
        if [ "$?" -eq "0" ]; then
            source $env_cmd
        fi
        cd - > /dev/null
        ;;
    --create | -c)
        (
            source "env_wrapper.sh"
            create_environment $2 $3
        )
        cd - > /dev/null
        ;;
    --interpreter | -i)
        (
            source "env_wrapper.sh"
            list_interpreters
        )
        cd - > /dev/null
        ;;
    --delete | -d)
        (
            source "env_wrapper.sh"
            delete_environment $2
        )
        cd - > /dev/null
        ;;

    --version | -v)
        (
            head -n1 "version"
        )
        cd - > /dev/null
        ;;
    --help | -h)
        help $0
        cd - > /dev/null
        ;;
    *)
        help $0
        cd - > /dev/null
        ;;
esac
